# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id = "rail_switch"
mod.name = "Rail Switch"
mod.group = "com.resalexanderccho.railswitch"
mod.version = "1.2.0"

deps.fabric_loader = "0.19.3"
loomx.loom_version = "1.17-SNAPSHOT"

["26.2"]
mod.mc_releases = ["26.2"]

[fabric."26.2"]
mod.mc_compat = "~26.2"
deps.fabric_api = "0.152.2+26.2"
